/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eurobisio;

import eurobisio.controllers.HasieraKud;
import eurobisio.controllers.ui.HasieraUI;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class Main extends Application {


    //UI
    private Parent hasiera;

    //Stage
    private Stage stage;

    //Kudeatzaileak
    private HasieraUI hasieraUI;

    //Sceneak
    private Scene hasieraScene;

    public static void Main(String[] args){
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage=primaryStage;
        pantailaGuztiakKargatu();

        stage.setTitle("Eurobisio");
        hasieraScene=new Scene(hasiera,300,300);
        stage.setScene(hasieraScene);
        stage.show();
    }

    public void pantailaGuztiakKargatu() throws IOException {
        FXMLLoader hasieraloader=new FXMLLoader(getClass().getResource("/hasierakoPanela.fxml"));
        hasiera=(Parent)hasieraloader.load();
        hasieraUI=hasieraloader.getController();
        hasieraUI.setMainApp(this);
    }
}
