/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eurobisio;

import eurobisio.controllers.ui.ErroreaUI;
import eurobisio.controllers.ui.HasieraUI;
import eurobisio.controllers.ui.HerrialdeHautatuUI;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class Main extends Application {

    //Stage
    private Stage stage;

    //parent
    private Parent hasiera;
    private Parent herrialdeHautatu;
    private Parent errorea;

    //Kudeatzaileak
    private HasieraUI hasieraUI;
    private HerrialdeHautatuUI herrialdeHautatuUI;
    private ErroreaUI erroreaUI;

    //Sceneak
    private Scene hasieraScene;
    private Scene herrialdeHautatuScene;
    private Scene erroreScene;

    public static void Main(String[] args){
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage=primaryStage;
        pantailaGuztiakKargatu();
        stage.setTitle("Eurobisio");

        //Scene guztiak kargatu
        hasieraScene=new Scene(hasiera,300,209);
        herrialdeHautatuScene=new Scene(herrialdeHautatu,600,400);

        stage.setScene(hasieraScene);
        stage.show();
    }

    public void pantailaGuztiakKargatu() throws IOException {
        //kargatu hasiera
        FXMLLoader hasieraLoader=new FXMLLoader(getClass().getResource("/scenak/hasierakoPanela.fxml"));
        hasiera=(Parent)hasieraLoader.load();
        hasieraUI=hasieraLoader.getController();
        hasieraUI.setMainApp(this);

        //kargatu herrialde hautatu
        FXMLLoader herrialdeHautatuLoader=new FXMLLoader(getClass().getResource("/scenak/herrialdeHautatuPanela.fxml"));
        herrialdeHautatu=(Parent) herrialdeHautatuLoader.load();
        herrialdeHautatuUI=herrialdeHautatuLoader.getController();
        herrialdeHautatuUI.setMainApp(this);

        //kargatu errorea
        FXMLLoader erroreLoader=new FXMLLoader(getClass().getResource("/scenak/erroreaPanlea.fxml"));
        errorea=(Parent) erroreLoader.load();
        erroreaUI=erroreLoader.getController();
        erroreaUI.setMainApp(this);
    }

    public void pantailaratuHerrialdeHautatu(){
        stage.setScene(herrialdeHautatuScene);
    }
}
